--CREARE LA TABLA MAESTRA
CREATE TABLE MASTERT
(
    DPIC VARCHAR2(50),
    PNOMBREC VARCHAR2(30),
    SNOMBREC VARCHAR2(30),
    PAPELLIDOC VARCHAR2(30),
    SAPELLIDOC VARCHAR2(30),
    NITC VARCHAR2(30),
    ECIVILC VARCHAR2(20),
    GENC VARCHAR(1),
    SUCURSAL INT,
    DIRSUCURSAL VARCHAR2(50),
    TELSUCURSAL VARCHAR2(10),
    DEPARTAMENTO VARCHAR2(30),
    MUNICIPIO VARCHAR2(30),
    DPIV VARCHAR2(50),
    PNOMBREV VARCHAR2(30),
    SNOMBREV VARCHAR2(30),
    PAPELLIDOV VARCHAR2(30),
    SAPELLIDOV VARCHAR2(30),
    NITV VARCHAR2(30),
    ECIVILV VARCHAR2(20),
    GENV VARCHAR(1),
    FACTURA VARCHAR2(30),
    FECHAFAC DATE,
    SERIE VARCHAR(1),
    CANTIDAD INT,
    COLOR VARCHAR(20),
    TALLA VARCHAR(10),
    NOMBRE_P VARCHAR2(50),
    PRECIO_P INT,
    CATEGORIA VARCHAR2(30)
);

--TABLA DEPARTAMENTO
CREATE TABLE DEPARTAMENTO
(
    ID_DEPTO INT NOT NULL,
    NOMBRE VARCHAR2(30),
    CONSTRAINT ID_DEPTO_PK
        PRIMARY KEY (ID_DEPTO)
);
CREATE SEQUENCE DEPTO_SEC START WITH 1;
CREATE OR REPLACE TRIGGER DEPTO_TRIG
BEFORE INSERT ON DEPARTAMENTO
FOR EACH ROW
BEGIN
    SELECT DEPTO_SEC.NEXTVAL
    INTO :new.ID_DEPTO
    FROM dual;
END;
/

--TABLA CATEGORIA
CREATE TABLE CATEGORIA
(
    ID_CATEGORIA INT NOT NULL,
    NOMBRE VARCHAR2(30),
    CONSTRAINT ID_CATEGORIA_PK
        PRIMARY KEY (ID_CATEGORIA)
);
CREATE SEQUENCE CATEGO_SEC START WITH 1;
CREATE OR REPLACE TRIGGER CATEGO_TRIG
BEFORE INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
    SELECT CATEGO_SEC.NEXTVAL
    INTO :new.ID_CATEGORIA
    FROM dual;
END;
/

--TABLA MUNICIPIO
CREATE TABLE MUNICIPIO
(
    ID_MUNICIPIO INT NOT NULL,
    NOMBRE VARCHAR2(30),
    ID_DEPTO INT,
    CONSTRAINT ID_MUNICIPIO_PK
        PRIMARY KEY (ID_MUNICIPIO),
    FOREIGN KEY (ID_DEPTO)
        REFERENCES DEPARTAMENTO(ID_DEPTO)
);
CREATE SEQUENCE MUNI_SEC START WITH 1;
CREATE OR REPLACE TRIGGER MUNI_TRIG
BEFORE INSERT ON MUNICIPIO
FOR EACH ROW
BEGIN
    SELECT MUNI_SEC.NEXTVAL
    INTO :new.ID_MUNICIPIO
    FROM dual;
END;
/

--CREAR TABLA PRODUCTO
CREATE TABLE PRODUCTO
(
    ID_PRODUCTO INT NOT NULL,
    NOMBRE VARCHAR2(50),
    ID_CATEGORIA INT,
    CONSTRAINT ID_PRODUCTO_PK
        PRIMARY KEY (ID_PRODUCTO),
    FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIA(ID_CATEGORIA)
);
CREATE SEQUENCE PRODUCTO_SEC START WITH 1;
CREATE OR REPLACE TRIGGER PRODUCTO_TRIG
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
    SELECT PRODUCTO_SEC.NEXTVAL
    INTO :new.ID_PRODUCTO
    FROM dual;
END;
/

--CREAR TABLA SUCURSAL
CREATE TABLE SUCURSAL
(
    ID_SUCURSAL INT NOT NULL,
    DIRECCION VARCHAR2(50),
    TELEFONO VARCHAR2(10),
    ID_MUNICIPIO INT,
    CONSTRAINT ID_SUCURSAL_PK
        PRIMARY KEY (ID_SUCURSAL),
    FOREIGN KEY (ID_MUNICIPIO)
        REFERENCES MUNICIPIO(ID_MUNICIPIO)
);


--TABLA VENDEDOR
CREATE TABLE USUARIO
(
    DPIV VARCHAR2(50),
    PNOMBRE VARCHAR2(30),
    SNOMBRE VARCHAR2(30),
    PAPELLIDO VARCHAR2(30),
    SAPELLIDO VARCHAR2(30),
    NIT VARCHAR2(30),
    ECIVIL VARCHAR2(20),
    GEN VARCHAR(1),
    TIPO INT DEFAULT 0,
    CONSTRAINT DPIV_PK
        PRIMARY KEY(DPIV)
);

--TABLA FACTURA QUE ES LA CABECERA
CREATE TABLE FACTURA
(
    NO_FACTURA VARCHAR2(30) NOT NULL,
    SERIE VARCHAR(1),
    FECHA DATE,
    DPI_USUARIO VARCHAR2(50),
    ID_SUCURSAL INT,
    CONSTRAINT NO_FACTURA_PK
        PRIMARY KEY (NO_FACTURA),
    FOREIGN KEY (DPI_USUARIO)
        REFERENCES USUARIO(DPIV),
    FOREIGN KEY (ID_SUCURSAL)
        REFERENCES SUCURSAL(ID_SUCURSAL)
);

--TABLA DETALLE
CREATE TABLE DETALLE_VENTA
(
    ID_DETALLE INT NOT NULL,
    NO_FACTURA VARCHAR2(30) NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    TALLA VARCHAR(10),
    COLOR VARCHAR(20),
    CANTIDAD INT,
    PRECIO INT,
    CONSTRAINT DETALLE_PK
        PRIMARY KEY (ID_DETALLE),
    FOREIGN KEY (NO_FACTURA)
        REFERENCES FACTURA(NO_FACTURA),
    FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
);
CREATE SEQUENCE DETALLE_SEC START WITH 1;
CREATE OR REPLACE TRIGGER DETALLE_TRIG
BEFORE INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    SELECT DETALLE_SEC.NEXTVAL
    INTO :new.ID_DETALLE
    FROM dual;
END;
/
INSERT INTO USUARIO(DPIV,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,NIT,ECIVIL,GEN,TIPO)
VALUES('1','VENEZ','VENEZ','VENEZ','VENEZ','DE_CHAMAS','ADMIN','M',1);
commit;
exit;